# Generated by Django 4.1.2 on 2022-10-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_post_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='priority',
            field=models.IntegerField(choices=[(0, 'General'), (1, 'Featured')], default=0),
        ),
    ]
